project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Avatar the Last Airbender"
  author:
    - Jason Cheung (jc6405)
    - Rogelio Lopez Camara (rl3499)
  repo-url: https://github.com/JasonCheung01/avatar_last_airbender
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


